# Generated by Django 6.0.6 on 2026-07-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Documentary', 'Documentary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
